<?php
return array(
	array(
		'from'=>'demo/banner-1.png',
		'to'=>'data/banner/banner-1.png'
	),
	array(
		'from'=>'demo/banner-2.png',
		'to'=>'data/banner/banner-2.png'
	),
	array(
		'from'=>'demo/banner-3.jpg',
		'to'=>'data/banner/banner-3.jpg'
	),
	array(
		'from'=>'demo/brand-1.jpg',
		'to'=>'data/brand/brand-1.jpg'
	),
	array(
		'from'=>'demo/brand-2.jpg',
		'to'=>'data/brand/brand-2.jpg'
	),
	array(
		'from'=>'demo/brand-3.jpg',
		'to'=>'data/brand/brand-3.jpg'
	),
	array(
		'from'=>'demo/brand-4.jpg',
		'to'=>'data/brand/brand-4.jpg'
	),
	array(
		'from'=>'demo/brand-5.jpg',
		'to'=>'data/brand/brand-5.jpg'
	),
	array(
		'from'=>'demo/brand-6.jpg',
		'to'=>'data/brand/brand-6.jpg'
	),
	array(
		'from'=>'demo/cate-banner.png',
		'to'=>'data/demo/cate-banner.png'
	),
	array(
		'from'=>'demo/cate-banner-2.png',
		'to'=>'data/demo/cate-banner-2.png'
	),
	array(
		'from'=>'demo/test-1.jpg',
		'to'=>'data/demo/test-1.jpg'
	),
	array(
		'from'=>'demo/test-2.jpg',
		'to'=>'data/demo/test-2.jpg'
	),
	array(
		'from'=>'demo/test-2-1.jpg',
		'to'=>'data/demo/test-2-1.jpg'
	),
	array(
		'from'=>'demo/test-2-2.jpg',
		'to'=>'data/demo/test-2-2.jpg'
	),
	array(
		'from'=>'demo/test-2-3.jpg',
		'to'=>'data/demo/test-2-3.jpg'
	),
	array(
		'from'=>'demo/test-2-4.jpg',
		'to'=>'data/demo/test-2-4.jpg'
	),
	array(
		'from'=>'demo/test-3.jpg',
		'to'=>'data/demo/test-3.jpg'
	),
	array(
		'from'=>'demo/test-4.jpg',
		'to'=>'data/demo/test-4.jpg'
	),
	array(
		'from'=>'demo/home-ad.png',
		'to'=>'data/home-ad.png'
	)
);